"""initial schema

Revision ID: ca2fb65d2c93
Revises: 
Create Date: 2026-06-28 23:21:53.487683
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ca2fb65d2c93'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_summaries'))
    )
    op.create_index(op.f('ix_daily_summaries_summary_date'), 'daily_summaries', ['summary_date'], unique=True)
    op.create_table('developers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developers')),
    sa.UniqueConstraint('name', name=op.f('uq_developers_name'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_projects_developer_id_developers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_developer_id'), 'projects', ['developer_id'], unique=False)
    op.create_table('whatsapp_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_external_id', sa.String(length=255), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_whatsapp_groups_developer_id_developers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_groups')),
    sa.UniqueConstraint('group_external_id', name=op.f('uq_whatsapp_groups_group_external_id'))
    )
    op.create_index(op.f('ix_whatsapp_groups_developer_id'), 'whatsapp_groups', ['developer_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_group_id', sa.Integer(), nullable=True),
    sa.Column('external_message_id', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'PDF', 'UNSUPPORTED', name='message_content_type'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['whatsapp_group_id'], ['whatsapp_groups.id'], name=op.f('fk_messages_whatsapp_group_id_whatsapp_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('external_message_id', name=op.f('uq_messages_external_message_id'))
    )
    op.create_index(op.f('ix_messages_content_hash'), 'messages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_messages_received_at'), 'messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_messages_whatsapp_group_id'), 'messages', ['whatsapp_group_id'], unique=False)
    op.create_table('commission_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('project_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('commission_value', sa.Text(), nullable=False),
    sa.Column('changed_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_commission_history_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_commission_history_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_history'))
    )
    op.create_index(op.f('ix_commission_history_changed_on'), 'commission_history', ['changed_on'], unique=False)
    op.create_index(op.f('ix_commission_history_message_id'), 'commission_history', ['message_id'], unique=False)
    op.create_index(op.f('ix_commission_history_project_id'), 'commission_history', ['project_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.Enum('LAUNCH', 'REQUEST', 'OFFER', 'COMMISSION_UPDATE', 'PRICE_UPDATE', 'BROCHURE', 'NEWS', 'GENERAL_INFORMATION', name='message_classification'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('raw_ai_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_extractions_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extractions'))
    )
    op.create_index(op.f('ix_extractions_content_hash'), 'extractions', ['content_hash'], unique=True)
    op.create_index(op.f('ix_extractions_message_id'), 'extractions', ['message_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('project_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('changed_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_price_history_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_price_history_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history'))
    )
    op.create_index(op.f('ix_price_history_changed_on'), 'price_history', ['changed_on'], unique=False)
    op.create_index(op.f('ix_price_history_message_id'), 'price_history', ['message_id'], unique=False)
    op.create_index(op.f('ix_price_history_project_id'), 'price_history', ['project_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('project_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('developer_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_documents_developer_id_developers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], name=op.f('fk_documents_extraction_id_extractions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_documents_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_documents_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_developer_id'), 'documents', ['developer_id'], unique=False)
    op.create_index(op.f('ix_documents_extraction_id'), 'documents', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_documents_message_id'), 'documents', ['message_id'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('extraction_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('original_ai_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], name=op.f('fk_extraction_corrections_extraction_id_extractions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_corrections'))
    )
    op.create_index(op.f('ix_extraction_corrections_extraction_id'), 'extraction_corrections', ['extraction_id'], unique=False)
    op.create_table('launches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_types', sa.Text(), nullable=True),
    sa.Column('starting_price', sa.Text(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('project_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('developer_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_launches_developer_id_developers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], name=op.f('fk_launches_extraction_id_extractions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_launches_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_launches_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_launches'))
    )
    op.create_index(op.f('ix_launches_developer_id'), 'launches', ['developer_id'], unique=False)
    op.create_index(op.f('ix_launches_extraction_id'), 'launches', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_launches_message_id'), 'launches', ['message_id'], unique=False)
    op.create_index(op.f('ix_launches_project_id'), 'launches', ['project_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_details', sa.Text(), nullable=True),
    sa.Column('down_payment', sa.Text(), nullable=True),
    sa.Column('installments', sa.Text(), nullable=True),
    sa.Column('contact_information', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('project_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('developer_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_offers_developer_id_developers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], name=op.f('fk_offers_extraction_id_extractions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_offers_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_offers_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.create_index(op.f('ix_offers_developer_id'), 'offers', ['developer_id'], unique=False)
    op.create_index(op.f('ix_offers_extraction_id'), 'offers', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_offers_message_id'), 'offers', ['message_id'], unique=False)
    op.create_index(op.f('ix_offers_project_id'), 'offers', ['project_id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('contact_information', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('project_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('developer_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('fk_requests_developer_id_developers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], name=op.f('fk_requests_extraction_id_extractions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_requests_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_requests_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    op.create_index(op.f('ix_requests_developer_id'), 'requests', ['developer_id'], unique=False)
    op.create_index(op.f('ix_requests_extraction_id'), 'requests', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_requests_message_id'), 'requests', ['message_id'], unique=False)
    op.create_index(op.f('ix_requests_project_id'), 'requests', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_project_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_message_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_extraction_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_developer_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_offers_project_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_message_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_extraction_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_developer_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_launches_project_id'), table_name='launches')
    op.drop_index(op.f('ix_launches_message_id'), table_name='launches')
    op.drop_index(op.f('ix_launches_extraction_id'), table_name='launches')
    op.drop_index(op.f('ix_launches_developer_id'), table_name='launches')
    op.drop_table('launches')
    op.drop_index(op.f('ix_extraction_corrections_extraction_id'), table_name='extraction_corrections')
    op.drop_table('extraction_corrections')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_message_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_extraction_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_developer_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_price_history_project_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_message_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_changed_on'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_extractions_message_id'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_content_hash'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_commission_history_project_id'), table_name='commission_history')
    op.drop_index(op.f('ix_commission_history_message_id'), table_name='commission_history')
    op.drop_index(op.f('ix_commission_history_changed_on'), table_name='commission_history')
    op.drop_table('commission_history')
    op.drop_index(op.f('ix_messages_whatsapp_group_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_received_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_content_hash'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_whatsapp_groups_developer_id'), table_name='whatsapp_groups')
    op.drop_table('whatsapp_groups')
    op.drop_index(op.f('ix_projects_developer_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('notifications')
    op.drop_table('developers')
    op.drop_index(op.f('ix_daily_summaries_summary_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
